services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    image: pytorch-dev:2.8.0-cu129
    container_name: pytorch-dev
    restart: unless-stopped
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TZ=Asia/Seoul
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
    ipc: host
    shm_size: "8g"
    working_dir: /workspace
    command: ["python","-m","jupyterlab",
              "--ip=0.0.0.0",
              "--port=8888",
              "--no-browser",
              "--allow-root"]
